### ISSUE TITLE
[FEATURE] Make word separation characters configurable

### ISSUE THREAD

**Issue by christianbltr** [tpwd/ke_search#19]
In some cases it would be helpful if e. g. characters like "." or "-" would not be treated as a word separator so that searchwords like `123-ABC` or `123.ABC` would not be treated as two words but one.

Use case would be e. g. serial numbers or product names which sometimes have a structure like that.

**Comment by dr2okevin** [comment]
Changelog and documentation claim that this feature is available since 5.1.0 but I don't get it to work in 5.1.2
I have configured .- as word chars and reindexed. But article numbers with these chars can't be found.
I have these Article numbers in the content field

> 6185135101
> 618.5135.101
> 618-5135-101
But only 6185135101 gets a result.

The hidden_content in the database contains only this.
> kann___46___ ___45___

Which seams to be the end of the first sentence of the article description that is also in the content field.

Maybe a issue with the regex in getAdditionalContent that it gets only the first match?

**Comment by christianbltr** [comment]
Yes indeed, the regex only fetched the first match. Thanks. This has been fixed in master and will be in version 5.1.3.
