### ISSUE TITLE
[FEATURE] Exclude files from indexing

### ISSUE THREAD

**Issue by christianbltr** [tpwd/ke_search#20]
As an editor I want to exclude files from indexing because I do not want the to show up in the search results.

There should be a checkbox "Enable indexing" in the file metadata which allows to exclude single files by deactivating that checkbox.

**Comment by brotkrueml** [comment]
What do you think about naming the option `Disable indexing` (as this would be the exception from the default rule, most of the time you want to enable indexing for an allowed file type). With `Enable indexing` you have to provide an upgrade wizard (which would be fine), otherwise the files do not get indexed anymore (like before the feature, which would be breaking).

**Comment by christianbltr** [comment]
Yes, I understand the point. But personally I do not like this type of a user interface very much. Then editor would need to *activate* the checkbox in order to *disable* the indexing.

Maybe we could name the field `exclude_from_indexing` internally and then use `invertStateDisplay`, as it's the same logic as in the `hidden` field of the `pages` table. Normally the editor should *activate* the field in order to *disable* the page, but `invertStateDisplay` turns that around.

This way the change would not be breaking as `exclude_from_indexing = 0` would be the default which would result in the same behaviour as before the patch.

https://docs.typo3.org/m/typo3/reference-tca/11.5/en-us/ColumnsConfig/Type/Check/Properties/InvertStateDisplay.html

![Auswahl_039](https://user-images.githubusercontent.com/11410553/150490341-f7717c7a-6cb0-4dd2-896e-7c71006a5a8f.png)

**Comment by christianbltr** [comment]
This feature has been merged to master and will be in version 4.6.0
