### ISSUE TITLE
Bad startingpoint if two Searchplugin on a page

### ISSUE THREAD

**Issue by phil64** [tpwd/ke_search#227]
My configuration:
- a general search plugin, injected in typoscript into the header of my page, to perform a search on the entire site. The list of results is on a general search page.
- a one-page search plugin for searching a certain part of my index, with an associated list of results.

My results list is configured to get the starting point of this search plugin, via loadFlexformsFromOtherCE.
But in the Db singleton class, the setPluginbase method is initialized with the first search plugin on the page, and therefore with the wrong starting point in the getWhere() method thereafter.

**Comment by phil64** [comment]
Actually, the problem is broader, because the entire configuration of the searchplugin of my page is ignored by the search request (the starting point, the filters...).
The only solution I currently have is to deactivate the "general" plugin injected in typoscript on the page.

**Comment by christianbltr** [comment]
I can see the point, but I think that's not so easy to resolve because of the the DB class being a singleton class as you already mentioned.

Would it be a workaround for you to add the search form in the header not via a plugin but via plain HTML as described in https://docs.typo3.org/p/tpwd/ke_search/main/en-us/Templating/Searchbox.html?

**Comment by phil64** [comment]
I understand that this is not easy to resolve.
I will try with the HTML solution.
For now, I just disabled the TS plugin injected on my specific page, it's ok for my use
