### ISSUE TITLE
Missing fe_groups property for files results in error

### ISSUE THREAD

**Issue by FLeudts** [tpwd/ke_search#84]
If the filemetadata extension isn't installed then files do not have a fe_groups property set. ([documentation](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Fal/Administration/Permissions.html#frontend-permissions))
In the storeFileInIndex Method of the IndexerBase ke_search accesses the array key without checking whether it is set. This causes errors.

The method also says:

``` Uses feGroups, starttime, enddtime, langauge and targetPage from the parent record.```

But in the code fe_groups are discarded if no file fe_groups are set
```        
 if ($fileProperties['fe_groups']) {
    if ($feGroups) {  
        $feGroupsContentArray = GeneralUtility::intExplode(',', $feGroups);  
        $feGroupsFileArray = GeneralUtility::intExplode(',', $fileProperties['fe_groups']);  
        $feGroups = implode(',', array_intersect($feGroupsContentArray, $feGroupsFileArray));  
    } else {  
        $feGroups = $fileProperties['fe_groups'];
     }  
}  
```

**Comment by christianbltr** [comment]
Checking the array key has been fixed in current master version.

$feGroups is a parameter of the function (https://github.com/tpwd/ke_search/blob/c2e4cacb06a0f9f2689cd87b46d1f97832872ff9/Classes/Indexer/IndexerBase.php#L571), so it is correct to skip setting $feGroups if $fileProperties['fe_groups'] is not set because then value originally passed to the function will be used.
